

/* Author : Subhash.K.U ( www.subhashku.com )
 * Copyright (C) MindSculptor Systems Pvt. Ltd (www.mindsculptorsys.com)
 */

/* SEMAPHORE OPERATION FUNCTIONS */

/*
     -semget(2)
     -semctl(2)
     -semop(2)
*/





#include<stdio.h>
#include<sys/types.h>
#include<sys/ipc.h>
#include<sys/sem.h>
#include<unistd.h>
#include<stdlib.h>

#define BUFFER "./SemaphoreTestFile"
union semun
{
	int val;
	struct semid_ds *buf;
	unsigned short *array;
};

int main(int argc, char *argv[])
{
	FILE *fptr;
	static struct sembuf acquire = {0, -1, SEM_UNDO};
	static struct sembuf release = {0,  1, SEM_UNDO};
	pid_t c_pid;
	key_t key;
	static unsigned short start_val[2] = {1, 0};
	int semid, producer = 0, i, n, p_sleep, c_sleep;
	union semun arg;
	enum{READ, MADE};

	if(argc != 2)
        {
                fprintf(stderr, "%s <time_to_sleep>\n", argv[0]);
                exit(1);
        }
	
	key = ftok(".", 'S');
	if((semid = semget(key, 2, IPC_CREAT | IPC_EXCL | 0666)) != -1)
	{
		producer = 1;
		arg.array = start_val;
		if(semctl(semid, 0, SETALL, arg) == -1)
		{
			perror("SEMCTL:SETALL");
			exit(2);
		}
	}
	else if((semid = semget(key, 2, 0666 )) == -1)
	{
		perror("SEMGET: CONSUMER OBTAINING SEMAPHORE");
		exit(3);
	}

	switch(producer)
	{
		case 1:
			p_sleep = atoi(argv[1]);
			srand((unsigned)getpid());
			
			for(i = 0; i < 10; i++)
			{
				sleep(p_sleep);
				n = rand() % 99 + 1;
				
				printf("A.THe number [%2d] generated by producer\n", n);
				acquire.sem_num = READ;
	
				if(semop(semid, &acquire, 1) == -1)
				{
					perror("SEMOP: PRODUCER: ACQUIRE");
					exit(4);
				}
				
				if((fptr = fopen(BUFFER, "w")) == NULL)  /*Creat a file without fail */
                                {
                                        perror(BUFFER);
                                        exit(5);
                                }
				
				fprintf(fptr, "%d\n", n);
				fclose(fptr);
				release.sem_num = MADE;
				printf("B.The Number [%2d] deposited by producer\n", n);
				
				if(semop(semid, &release, 1) == -1)
                                {
                                        perror("SEMOP: PRODUCER: RELEASE");
                                        exit(6);
                                }
			}
		
			sleep(5);
			if(semctl(semid, 0, IPC_RMID, 0) == -1)
                        {
                                 perror("SEMCTL: PRODUCERAL IPC_RMID");
                                 exit(7);
                        }
			printf("Semaphore Removed\n");
			break;

		case 0:
			c_sleep = atoi(argv[1]);
			c_pid = getpid();
			
			while(1)
			{
				sleep(c_sleep);
				acquire.sem_num = MADE;
				
				if(semop(semid, &acquire, 1) == -1)
                                {
                                        perror("SEMOP: CONSUMER: ACQUIRE");
                                        exit(8);
                                }
				
				if((fptr = fopen(BUFFER, "r")) == NULL)
                                {
                                        perror("BUFFER");
                                        exit(9);
                                }
				
				fptr = fopen(BUFFER, "r");
				fscanf(fptr, "%d", &n);
				fclose(fptr);
				release.sem_num = READ;

				if(semop(semid, &release, 1) == -1)
                                {
                                        perror("SEMOP: CONSUMER: RELEASE");
                                        exit(10);
                                }
				printf("C.THe number [%2d] obtained by consumer %6d\n", n, c_pid);
			}
	}
	exit(0);
}
